include_directories("${CMAKE_CURRENT_SOURCE_DIR}")

add_subdirectory("core")
add_subdirectory("procedural")
add_subdirectory("resource")
add_subdirectory("math")
add_subdirectory("system")
add_subdirectory("platform")
add_subdirectory("network")
add_subdirectory("lockstep")
add_subdirectory("store")
add_subdirectory("vendor")
add_subdirectory("graphics")
add_subdirectory("manager")
add_subdirectory("script")
add_subdirectory("application")
add_subdirectory("framework")
