add_library(leaf-procedural STATIC scratch.cpp)
add_library(leaf::procedural ALIAS leaf-procedural)
target_include_directories(leaf-procedural PUBLIC "${PROJECT_SOURCE_DIR}/include")
target_link_libraries(leaf-procedural PUBLIC leaf::core)
option(LEAF_BUILD_BENCHMARKS "Build Leaf benchmarks" OFF)
if(LEAF_BUILD_BENCHMARKS)
    add_executable(leaf-procedural-benchmark "${PROJECT_SOURCE_DIR}/benchmarks/procedural.cpp")
    target_link_libraries(leaf-procedural-benchmark PRIVATE leaf::procedural)
endif()
